### ISSUE TITLE
📢 All issues and PRs on hold! 📢

### ISSUE THREAD

**Issue by walkxcode** [walkxcode/dashboard-icons#316]
I am working on a new standard for this repo. All icons will now have to fit this ruleset.

- Each `PNG` has to have a height of exactly `512px`. (No upscales, if one cannot be found, a smaller height will be accepted.)
- Each icon has to include both a `PNG` and `SVG` version. (Unless a `SVG` cannot be found.)
- Icons will have to be named after their full name. Spaces are replaced by dashes. (Example. Facebook Messenger ⇾ `facebook-messenger.png`).
- Icons in monochrome color will be defaulted to a dark version. Light versions will be named `service-light.png`.

I am currently re-adding each icon _manually_ to fit this standard. This will take me a couple of weeks and to avoid conflicts and confusion I have decided to temporarily put issues and PRs on hold. 
Please understand my decision.

Greetings,
Walkx

**Comment by nomandera** [comment]
I applaud the steps to increase standardization. Can I ask a few questions and make a couple of suggestions based on confusion I had over my latest PR which are not clarified by the new standard.

1. Is the 512px height the logo itself. i.e. most current icons seem to choose an arbitrary smaller logo size within a square transparent/whitespace. This effectively makes the icon size variable +/- 20%
2. If the logo does not lend itself to a square icon how should this be handled. Related to the question above this could make the icon width many times the height and still be withing specification.
3. It is understood that the background should be transparent (which depending on the answer to question 1 may be very few pixels) but what about voids within the logo? A good example is the void in the [Amazon A](https://github.com/walkxcode/dashboard-icons/blob/main/png/amazon.png) although there are many more subtle examples.
4. When the SVG is uploaded is there a actual need to upload a PNG since an absolutely perfect PNG could be generated by the system itself. This would avoid  user variance in areas such as compression and colour space etc
5. If only a PNG is available should it be optimsed by the user using something like tinypng. Like point 4 there is a stong argument to be made that if the logo is square then the unadulterated upstream master copy should be uploaded so that the system can size and optimse it based on a common, potentially evolving spec, rather than rely on varying user skills and choices.

**Comment by walkxcode** [comment]
> I applaud the steps to increase standardization. Can I ask a few questions and make a couple of suggestions based on confusion I had over my latest PR which are not clarified by the new standard.
> 
> 1. Is the 512px height the logo itself. i.e. most current icons seem to choose an arbitrary smaller logo size within a square transparent/whitespace. This effectively makes the icon size variable +/- 20%
> 2. If the logo does not lend itself to a square icon how should this be handled. Related to the question above this could make the icon width many times the height and still be withing specification.
> 3. It is understood that the background should be transparent (which depending on the answer to question 1 may be very few pixels) but what about voids within the logo? A good example is the void in the [Amazon A](https://github.com/walkxcode/dashboard-icons/blob/main/png/amazon.png?rgh-link-date=2023-03-10T08%3A13%3A09Z) although there are many more subtle examples.
> 4. When the SVG is uploaded is there a actual need to upload a PNG since an absolutely perfect PNG could be generated by the system itself. This would avoid  user variance in areas such as compression and colour space etc
> 5. If only a PNG is available should it be optimsed by the user using something like tinypng. Like point 4 there is a stong argument to be made that if the logo is square then the unadulterated upstream master copy should be uploaded so that the system can size and optimse it based on a common, potentially evolving spec, rather than rely on varying user skills and choices.

I'll write an extensive answer to this as soon as possible. But I just wanted to give a quick update. I've paused searching icons for a little bit as I have been sick, but I will continue searching again tomorrow. If anyone wants to help out with searching, please contact me on Discord. `Walkx#2159`

**Comment by walkxcode** [comment]
Just about 200 icons left to do! Hoping to get everything done in 2 days.

**Comment by walkxcode** [comment]
I'm finally done with converting all icons! 🥳🎉 I am planning on adding some new ones and I will update the documentation soon. 

It would help me out a lot if you guys could help look for any potential errors in my PR. (Broken SVG/PNGs, wrong names/spelling, etc.). Checkout the PR here 👉 https://github.com/walkxcode/dashboard-icons/pull/353

**Comment by walkxcode** [comment]
> 3. It is understood that the background should be transparent (which depending on the answer to question 1 may be very few pixels) but what about voids within the logo? A good example is the void in the [Amazon A](https://github.com/walkxcode/dashboard-icons/blob/main/png/amazon.png?rgh-link-date=2023-03-10T08%3A13%3A09Z) although there are many more subtle examples.

Hey, just to come back to this. What exactly do you mean with void?

> 4. When the SVG is uploaded is there a actual need to upload a PNG since an absolutely perfect PNG could be generated by the system itself. This would avoid  user variance in areas such as compression and colour space etc

I will provide rules for converting in the Contribution guide.

> 5. If only a PNG is available should it be optimsed by the user using something like tinypng. Like point 4 there is a stong argument to be made that if the logo is square then the unadulterated upstream master copy should be uploaded so that the system can size and optimse it based on a common, potentially evolving spec, rather than rely on varying user skills and choices.

All icons are automatically compressed by @ImgBotApp 

@nomandera

**Comment by nomandera** [comment]
Thanks for the update and all the work.

To answer specifically what I "mean with void?" is easiest done with a hypothetical example:
![amazon2](https://user-images.githubusercontent.com/1133344/232313776-8f4c03b5-9da6-4f92-a3f2-98df215a7b5e.png)

The red "void" in the logo should normally be part of the transparent background. This is not always the case with all logo designs but what is often the case is that people will fill voids based on their personal taste.

This should ideally be covered with a simple rule along the lines of "voids should be transparent unless the original design specifically requires it not to be"

**Comment by walkxcode** [comment]
> This should ideally be covered with a simple rule along the lines of "voids should be transparent unless the original design specifically requires it not to be"

I think this is pretty common knowledge, and I haven't seen this be a big problem. But if you want to write up something for it and make a PR, go for it!

**Comment by nomandera** [comment]
Your recent work changes so much in the project its like a complete refresh. Lets leave it this now and address things if they become actual rather than theoretical problems.
