### ISSUE TITLE
Icon Labels to allow searching

### ISSUE THREAD

**Issue by pradt** [walkxcode/dashboard-icons#436]
I was just setting up my dashy dashboard and I was using the icons for Homelab, since I was setting up everything up from scratch it was really time consuming/annoying trying to find the appropriate icon. 

Just wondering whether labels can be added so that CTRL+F can be used to find the icon ? Happy to do this, I noticed that the images have alt describing the images. 

Alternatively just use the function at https://jsfiddle.net/prad/49um7agz/ 

Take the raw content and paste it into the textarea and click on the convert button and it will undertake the conversion. 

Thanks

**Comment by walkxcode** [comment]
Hi, this would be a great addition. This would have to be added into the ci.py file (https://github.com/walkxcode/dashboard-icons/blob/main/config/ci.py). It would be great if the icons could be in boxes with the label underneath, but I don't know if this is possible due to some icons being really wide. 

I would be really happy to let you do this, so go ahead!

**Comment by jag-k** [comment]
@pradt @walkxcode you can check my PR (#448). I think this is fix your problem.
