### ISSUE TITLE
PNG directory has been truncated to 1,000 entries

### ISSUE THREAD

**Issue by kmichels** [walkxcode/dashboard-icons#705]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

..

### Icon(s)

<img width="1629" alt="Screenshot 2024-05-19 at 15 02 46" src="https://github.com/walkxcode/dashboard-icons/assets/2066586/db72225e-8693-4060-8e00-f6c086aac3e7">

**Comment by walkxcode** [comment]
You can use the search bar to find images if needed. Otherwise, go to the icons page:

⚠️ Warning! Visiting this page will load every single icon in the repository. This may cause:

- 📉 Excessive data usage.
- 💻 System slowdowns.
	- 🌐 Browser crashes.
If your device cannot handle loading more than 1000 images or if you are on a limited data connection, we advise against visiting this page.

➡️ Click [here](https://github.com/walkxcode/dashboard-icons/blob/main/ICONS.md) to view all icons.
